### ISSUE TITLE
Not able to update the results of test cases as pass/fail in Testrail

### ISSUE THREAD

**Issue by sharmadeepak43** [VoloBro/testrail-api-client#5]
I am not able to update the proper results in Testrail. How can I get the exact status if particular test case. I tried with addResultsForCases but seems it that method we need to provide the status id as dynamic. So how can we get this status id as dynamic as there is no such method to get the execution result status.
If I pass status id as 1, it will update the status as pass for all the tests in the suite which is resulted into incorrect mapping.
Could you please help me in that.

**Comment by VoloBro** [comment]
hi @sharmadeepak43 , for the list of supported statuses check out TestRail api guide. https://www.gurock.com/testrail/docs/api/reference/results#Request%20fields

for the 
![image](https://user-images.githubusercontent.com/14946112/108891974-55a48680-75dd-11eb-96cd-aa9f2f8f6f94.png)
